#ifndef PCSTREAM_CORE_H
#define PCSTREAM_CORE_H

#include <stddef.h>
#include <stdint.h>

typedef uint32_t PCSTREAM_RET;
typedef int64_t  PCSTREAM_BW; // Bytes/s
typedef float    PCSTREAM_RATIO;
typedef uint64_t PCSTREAM_COUNT;
typedef uint8_t  PCSTREAM_LOD_VERSION;
typedef uint8_t  PCSTREAM_BOOL;

#define PCSTREAM_UNINITIALIZED -1
#define PCSTREAM_TRUE          (1)
#define PCSTREAM_FALSE         (0)
#define PCSTREAM_MAX_BUFF      0xffff
#define PCSTREAM_BW_DEFAULT    PCSTREAM_UNINITIALIZED
#define PCSTREAM_RATIO_DEFAULT PCSTREAM_UNINITIALIZED

#ifdef __cplusplus
#define PCSTREAM_NULL nullptr
#else
#define PCSTREAM_NULL ((void *)0)
#endif

#define PCSTREAM_RET_FAIL    0x00
#define PCSTREAM_RET_SUCCESS 0x01

#define PCSTREAM_FLOAT_ERROR 1e-6f

typedef enum
{
  PCSTREAM_BW_ESTIMATOR_HARMONIC = 1
} PCSTREAM_BW_ESTIMATOR;

typedef enum
{
  PCSTREAM_HTTP_1_1,
  PCSTREAM_HTTP_2_0,
  PCSTREAM_HTTP_3_0
} PCSTREAM_HTTP_VERSION;

typedef enum
{
  PCSTREAM_LOD_SELECTOR_DP_BASED = 1,
  PCSTREAM_LOD_SELECTOR_LM_BASED,
  PCSTREAM_LOD_SELECTOR_EQUAL,
  PCSTREAM_LOD_SELECTOR_HYBRID,
} PCSTREAM_LOD_SELECTOR;

typedef enum
{
  PCSTREAM_REQUEST_HANDLER_H2 = 1
} PCSTREAM_REQUEST_HANDLER;
typedef enum
{
  PCSTREAM_VIEWPORT_ESTIMATOR_VELOCITY = 1
} PCSTREAM_VIEWPORT_ESTIMATOR;

typedef enum
{
  PCSTREAM_VISIBILITY_COMPUTER_HULL = 1
} PCSTREAM_VISIBILITY;

typedef enum
{
  PCSTREAM_VIDEO_DECODER_MPEG_VPCC,
  PCSTREAM_VIDEO_DECODER_MPEG_GPCC,
  PCSTREAM_VIDEO_DECODER_GOOGLE_DRACO,
  PCSTREAM_VIDEO_DECODER_PCL,
  PCSTREAM_VIDEO_DECODER_COUNT
} PCSTREAM_VIDEO_DECODER;

typedef int16_t pcs_mpeg_vpcc_coord_t;
typedef float   pcs_mpeg_gpcc_coord_t;
typedef float   pcs_google_draco_coord_t;
typedef float   pcs_pcl_coord_t;
// typedef enum
// {
//   PCSTREAM_TYPE_FLOAT32,
//   PCSTREAM_TYPE_FLOAT64,
//   PCSTREAM_TYPE_INT8,
//   PCSTREAM_TYPE_UINT8,
//   PCSTREAM_TYPE_INT16,
//   PCSTREAM_TYPE_UINT16,
//   PCSTREAM_TYPE_INT32,
//   PCSTREAM_TYPE_UINT32,
//   PCSTREAM_TYPE_INT64,
//   PCSTREAM_TYPE_UINT64,
//   PCSTREAM_TYPE_COUNT
// } PCSTREAM_TYPE;
//
// extern const size_t pcs_type_size_g[PCSTEAM_TYPE_COUNT];
// extern const PCSTREAM_TYPE
//     pcs_pos_type_g[PCSTREAM_VIDEO_DECODER_COUNT];
#endif
